### PR TITLE
feat(dresscode updates): use dress code grid in the header.

### PR DESCRIPTION
**Pull request by sambhav-gore**
This change depends on unreleased dress code changes. 

The markup is cleaner and easier to maintain in future because of this (see image below). All items in the header are aligned using the dc grid. Other styles such as menus and drop downs are left untouched. 
Some unused (or overriding) styles are removed from solution-center-header styles.

header-markup

### CODE REVIEW

**Comment by gregdeane** [comment]
@sambhav-gore Which dress-code branch/version is required to see these header changes?

**Comment by sambhav-gore** [comment]
@gregdeane latest develop branch through bower link for testing.

**Comment by gregdeane** [comment]
Awesome update! I appreciate your dedication to this flex grid stuff. A couple issues below:

**iPhone 5 - Landscape**
Note the issues with nav overhang and user/help links breaking to next line.

image

**iPhone 6 - Landscape**
Perhaps we should just say "Brand" with the arrow in this view? Or better yet, just say "Brand" all the time? I'm not sure "Name" adds much to understanding what this link does.

image

@sambhav-gore @cjhowald @dami-gg What do you think about "Brand Name" being shortened to "Brand" in all views?

**Comment by cjhowald** [comment]
"Brand name" is just a placeholder in the demo. It would be replaced by a real brand name.

**Comment by gregdeane** [comment]
@cjhowald Thanks for the tip. ;)

**Comment by dami-gg** [comment]
Anyway we should consider how to handle long brand names on those views, otherwise they look broken, e.g.: "Polo Sport Ralph Lauren" @gabrielhl @gloriarupprecht

**Comment by sambhav-gore** [comment]
@gregdeane Thanks for checking it. Our current breakpoints are too small I will increase those and do some adjustments to get it working all of the time.

**Comment by gabrielhl** [comment]
To fix this we need to either switch to the hamburger menu before this happens. So probably at tablet size ~768px.

**Comment by sambhav-gore** [comment]
@gregdeane @gabrielhl I made some changes and restricted the max width of the brand name on smaller screens. increased overall breakpoint (for mobiles) to 600px. Following are a few screengrabs:


**iPhone 5**
iphone-5

**iPhone 6 Landscape**
iphone-landscape

**When the brand name is too big (desktop)**
long-brand-name

**When the brand name is too big (smaller screen sizes)**
responsive-brand-name

**Comment by gregdeane** [comment]
@sambhav-gore Checked the updates. Look good.

**Comment by dami-gg** [comment]
Great improvement Sambhav!

**Comment by dami-gg** [comment]
:+1:

**Comment by gloriarupprecht** [comment]
very nice @sambhav-gore

**Comment by gregdeane** [comment]
👍

**Comment by gabrielhl** [comment]
Late to the party but looks great @sambhav-gore!

**Pull request merged**
