### PR TITLE
Show diacritics in Brand Name. Close #92

### LINKED ISSUE #92: Umlauts in brand name are cut off
When a brand name contains some special characters (like german umlauts), they are cut off.
Probably overflow: hidden issue.

header-umlauts-cut-off

### PR DESCRIPTION
**Pull request by gabrielhl**
Fixes #92 

- Changed the line-height to fit umlauts and other diacritics.
- Adjusted the position of the arrow to adapt to the new line-height.

### CODE REVIEW

**Comment by cjhowald** [comment]
@gabrielhl Please revert `dist` changes (we never update `dist` in a PR, only when building a new release).

**Comment by cjhowald** [comment]
Updating from master since it is out of date.

**Comment by gabrielhl** [comment]
Thanks for updating the branch @cjhowald. Strangely git has picked up a .DS_Store file even though it's supposed to be ignored according to .gitignore :( I've removed it.

**Comment by cjhowald** [comment]
Manually testing looks good - nice work @gabrielhl! Confirmed all tests pass and works in Chrome, Firefox, and Safari.

Added a small commit of my own - just an npm task rename that had been bothering me.

**Comment by cjhowald** [comment]
👍

**Comment by gabrielhl** [comment]
👍

**Pull request merged**
