### PR TITLE
Feature/update module name 64

### LINKED ISSUE #64: Change angular module naming
See https://github.com/zalando-incubator/solution-center-login/issues/30 for more info.

### PR DESCRIPTION
**Pull request by gregdeane**
Closes #64 

This release will be `major` with breaking changes regarding module/component naming.

~~@cjhowald, @sambhav-gore, @dami-gg can one of you take a peak and see why `click-outside` directive no longer works? I'm unable to determine the issue.~~ **Nevermind, found the issue.**

### CODE REVIEW

**Comment by gregdeane** [comment]
Thumbs downing for now. See initial comment.

**Comment by gregdeane** [comment]
👎

**Comment by cjhowald** [comment]
Revert `dist/` changes.

**Comment by gregdeane** [comment]
@cjhowald You mean put the dist files back?

**Comment by cjhowald** [comment]
@gregdeane Yes, do not commit any changes to `dist`. Right now you have committed them as deleted. The release process should handle all changes to `dist`.

**Comment by gregdeane** [comment]
@cjhowald done. Thx!

**Comment by gregdeane** [comment]
👍

**Pull request merged**
