### PR TITLE
feat(icons): extract user and help icons from dress code to avoid inc…

### LINKED ISSUE #122: Extract user and help icons from dress code and use them directly
To avoid problems when teams update to the new version of Dress Code (2.0.0) which includes new icons that don't look good in the header and may be overridden we must copy the current style of those icons (any previous version of Dress Code) and set them as own styles of the Header instead of using them directly from Dress Code

### PR DESCRIPTION
**Pull request by dami-gg**
…ompatibilities

Closes #122

### CODE REVIEW

**Comment by gregdeane** [comment]
👍

**Comment by dami-gg** [comment]
Since when do we run tests in the dist files? :/

**Comment by gregdeane** [comment]
If I remember correctly, it's because it was difficult to get the individual files imported for testing using Browserify. I can't really remember though.

At least the tests are being run on the actual files that we distribute. :D

**Comment by cjhowald** [comment]
Tests were all failing (also locally) due to a breaking change from angular 1.6. Fixed.

**Comment by dami-gg** [comment]
Oh I see, the carrot character in package.json again... It didn't fail to me locally but I guess when you do NPM install it takes 1.6

Since we're deprecating this library soon I'll fix the version to 1.5.9 there to avoid these kind of problems in the future

**Comment by dami-gg** [comment]
:+1:

**Comment by cjhowald** [comment]
Highlight is broken now:

image

**Comment by cjhowald** [comment]
👍

**Comment by dami-gg** [comment]
:+1:

**Pull request merged**
