### PR TITLE
chore(autoprefix): add autoprefixer for css

### PR DESCRIPTION
**Pull request by gregdeane**
Used `last 3 versions` because with `last 2 versions` -webkit prefixes weren't being added.

### CODE REVIEW

**Comment by gregdeane** [comment]
Also, tested on El Capitan using Safari 9.0.3 (11601.4.4). However, I spoofed the user agent, using:

`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/10600.8.9 (KHTML, like Gecko) Version/8.0.8 Safari/10600.8.9`

Not sure if this does anything but the header looks good.

**Comment by cjhowald** [comment]
Changing the user agent string doesn't seem to have an impact. But the prefixes should solve the issue anyway.

Please revert the changes to `dist/` and push just the source changes. `dist` only gets updated when we release a new version (i.e. after the branch merges).

**Comment by cjhowald** [comment]
Also update the bower.json to include the new dev dependency.

**Comment by gregdeane** [comment]
Reverted /dist files and discussed in person regarding the bower.json comment.

**Pull request merged**
