### PR TITLE
fix(menu): fix in highlight of selected module

### PR DESCRIPTION
**Pull request by sambhav-gore**
After the change:
*Mobile:*
mobile

*Desktop:*
normal

### CODE REVIEW

**Comment by sambhav-gore** [comment]
@gabrielhl Please see if it looks okay ?

**Comment by dami-gg** [comment]
it looks really great now!

**Comment by dami-gg** [comment]
:+1:

**Comment by gregdeane** [comment]
Looks awesome man. 👍

**Comment by gabrielhl** [comment]
Right now I can't run it locally to check but looks good in the screenshot!

On Tuesday, 21 June 2016, Sambhav Gore <notifications@github.com> wrote:

> @gabrielhl <https://github.com/gabrielhl> Please see if it looks okay ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/zalando-incubator/solution-center-header/pull/51#issuecomment-227439702>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAB5OosRGkf_CQLYIxO2awrsbEuQh4U2ks5qN-digaJpZM4I6u5D>
> .
>


-- 

Gabriel Lovato
Visual Designer / Brand Solutions
Zalando SE

POSTAL ADDRESS
Zalando SE
11501 Berlin

OFFICE
Zalando SE
Mollstraße 1
10178 Berlin
Germany

Fax: +493027594693
Email: gabriel.lovato@zalando.de
Web: corporate.zalando.de
Jobs: jobs.zalando.de

Zalando SE, Tamara-Danz-Straße 1, 10243 Berlin
Company registration: Amtsgericht Charlottenburg, HRB 158855 B
Tax ID: 29/560/00596 * VAT registration number: DE 260543043
Management Board: Robert Gentz, David Schneider, Rubin Ritter
Chairperson of the Supervisory Board: Cristina Stenbeck
Registered office: Berlin

**Pull request merged**
